/* GENERATED by .workbuddy-ai/tools/selfhost-fonts.mjs — do not edit by hand.
   Faces used by above-the-fold text; layout.jsx preloads them so the hero
   headline paints in Cairo instead of swapping in from the fallback. */

export const PRELOAD_FONTS = [
    '/assets/fonts/cairo-800-normal-arabic-SLXVc1nY6HkvangtZmpQdkhzfH5lkSscQyyS4J0.woff2',
    '/assets/fonts/cairo-900-normal-arabic-SLXVc1nY6HkvangtZmpQdkhzfH5lkSscQyyS4J0.woff2',
];
